# Generated by Django 5.0.6 on 2024-06-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_product_productsubcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.ManyToManyField(
                related_name="products",
                to="product.subcategory",
                verbose_name="subcategory",
            ),
        ),
        migrations.DeleteModel(
            name="ProductSubCategory",
        ),
    ]
