# Generated by Django 5.0.6 on 2024-06-22 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_unique_product_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('name', 'category')},
        ),
    ]
