# Generated by Django 5.0.6 on 2024-06-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_role_userrole"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="date_joined",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="accounts.role",
                verbose_name="role",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name="UserRole",
        ),
    ]
